FROM node:8 as builder

ARG PLUGIN_NAME
ARG BACKEND_URL
ARG BUILD_ENV

ENV PLUGIN_NAME=$PLUGIN_NAME
ENV BACKEND_URL=$BACKEND_URL
ENV BUILD_ENV=$BUILD_ENV

RUN echo NODE_ENV

ENV NODE_ENV=development

RUN mkdir /app
WORKDIR /app
COPY . .

RUN npm i
RUN npm run build

FROM node:8

ARG PLUGIN_NAME
ARG HOSTNAME
ARG PORT
ARG PLUGIN_NAME
ARG BACKEND_URL
ARG NODE_ENV
ARG BABEL_DISABLE_CACHE
ARG BABEL_CACHE_PATH

ENV PLUGIN_NAME=$PLUGIN_NAME
ENV HOSTNAME=$HOSTNAME
ENV PORT=$PORT
ENV PLUGIN_NAME=$PLUGIN_NAME
ENV BACKEND_URL=$BACKEND_URL
ENV NODE_ENV=$NODE_ENV
ENV BABEL_CACHE_PATH=$BABEL_CACHE_PATH
ENV BABEL_DISABLE_CACHE=$BABEL_DISABLE_CACHE

RUN mkdir /app
WORKDIR /app
COPY . .
RUN npm i
COPY --from=builder /app/dist /app/dist

ENTRYPOINT [ "npm", "start" ]